### ISSUE TITLE
add video and materials from the first open lecture (docker + django + angular...)

### ISSUE THREAD

**Issue by suchov** [Kottans/kottans-calendar#2]
@pogorelov-ss @lempiy can you help us with that?

**Comment by pogorelov-ss** [comment]
hm link to video https://youtu.be/girLVdFgjjI
code https://github.com/pogorelov-ss/ptTaskLine 
slides .....

**Comment by pogorelov-ss** [comment]
and what is this? [calendar](http://kottans.org/kottans-calendar) 2 tabs ....  Vintage design?

**Comment by AMashoshyna** [comment]
@pogorelov-ss thanks!

**Comment by suchov** [comment]
@AMashoshyna you'll create a PR for this issue?

**Comment by AMashoshyna** [comment]
@AMashoshyna sure
